#
# Module manifest for module 'UEFIv2'
#
# Generated by: Michael Niehaus
#
# Generated on: 10/5/2019
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'UEFIv2'

# Version number of this module.
ModuleVersion = '3.0'

# Supported PSEditions
CompatiblePSEditions = 'Desktop'

# ID used to uniquely identify this module
GUID = 'b364b43d-350b-4a3b-9b98-f6f4a6ad0257'

# Author of this module
Author = 'Michael Niehaus'

# Company or vendor of this module
CompanyName = ''

# Copyright statement for this module
Copyright = 'Copyright (c) 2025 by Michael Niehaus, using MIT license'

# Description of the functionality provided by this module
Description = 'Module for interacting with UEFI from PowerShell'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-UEFIVariable', 'Set-UEFIVariable', 'Set-LHSTokenPrivilege', 'Get-UEFISecureBootCerts', 'Get-UEFIBootEntry', 'Add-UEFIBootEntry', 'Remove-UEFIBootEntry'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/mtniehaus/UEFIv2/blob/main/license.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/mtniehaus/UEFIv2'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
Version 3.0: Added PowerShell 7 compatibility
Version 2.8: Added additional logic for boot entries
Version 2.7: Added partition parameter index parameter for cases where the index and number aren't the same (e.g. shrunk/new partition)
Version 2.6: Added partition parameter for UEFI boot entry creation
Version 2.5: Added UEFI boot entry cmdlets
Version 2.4: Fixed byte array size
Version 2.3: Added the ability to display any UEFI secure boot variable
Version 2.2: Added Get-UEFISecureBootCerts cmdlet
Version 2.1: Added logic to allocate a bigger buffer for Get-UEFIVariable
Version 2.0: Added -All switch to display a full list of UEFI variable names
Version 1.1: Fixed help examples
Version 1.0: Published initial version
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

